grails-app/domain/docker/registry/web/Registry.groovy
package docker.registry.web

import docker.registry.web.support.RegistryAction

import javax.swing.text.html.Option

class Registry {
    String host = "localhost"
    int port
    String apiVersion = "v1"
    String username
    String password
    String protocol = "http"

    def repositoryService

    static constraints = {
        username nullable: true
        password nullable: true
    }

    static transients = ['toUrl', 'repositories', 'ping', 'fromUrl']

    String toUrl() {
        def resolvedPort = this.port == 80 || this.port <= 0 ? "" : ":" + this.port;
        def urlString = "${this.protocol}://${this.host}${resolvedPort}/${this.apiVersion}"
        if (username) {
            if (password) urlString = urlString.replace("://", "://$username:$password@")
            else urlString = urlString.replace("://", "://$username@")
        }
        urlString
    }

    URL toUrl(RegistryAction registryAction) {
        switch (registryAction) {
            case RegistryAction.PING: return new URL(this.apiVersion == "v1" ? "${this.toUrl()}/_ping" : "${this.toUrl()}/_catalog")
            case RegistryAction.SEARCH: return new URL(this.apiVersion == "v1" ? "${this.toUrl()}/search" : "${this.toUrl()}/_catalog")
            default: return null;
        }
    }

    def getRepositories() {
        repositoryService.index(this)
    }

    def ping() {
        repositoryService.ping(this)
    }

    /**
     * Static factory method for creating an instance from a URL.
     * @param urlStr a url in the format: http://hostOrIP:OptionalPort/v1/
     **/
    static Optional<Registry> fromUrl(final String urlStr) {
        if (urlStr?.endsWith("/v1/") || urlStr?.endsWith("/v2/")) {
            def url = urlStr.toURL()
            if (url) {
                def auth = url.userInfo?.split(":")
                return Optional.of(new Registry(
                        protocol: url.protocol,
                        host: url.host,
                        port: url.port == -1 ? 80 : url.port,
                        apiVersion: url.path.replaceAll("\\p{Punct}", ""),
                        username: auth?.length > 0 ? auth[0] : null,
                        password: auth?.length > 1 ? auth[1] : null
                ))
            }
        }
        Optional.empty()
    }

    @Override
    public String toString() {
        return "Registry{" +
                "id=" + id +
                ", protocol='" + protocol + '\'' +
                ", host='" + host + '\'' +
                ", port=" + port +
                ", apiVersion='" + apiVersion + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password?.replaceAll("(?s).", "*") + '\'' +
                ", repositoryService=" + repositoryService +
                ", version=" + version +
                '}';
    }
}

grails-app/domain/docker/registry/web/Role.groovy
package docker.registry.web

class Role {

	String authority

	static mapping = {
		cache true
	}

	static constraints = {
		authority blank: false, unique: true
	}
}

grails-app/domain/docker/registry/web/Setting.groovy
package docker.registry.web

class Setting {

    String name
    String value

    static constraints = {
    }
}

grails-app/domain/docker/registry/web/User.groovy
package docker.registry.web

class User {

	transient springSecurityService

	String username
	String password
	boolean enabled = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired

	static transients = ['springSecurityService']

	static constraints = {
		username blank: false, unique: true
		password blank: false
	}

	static mapping = {
		password column: '`password`'
	}

	Set<Role> getAuthorities() {
		UserRole.findAllByUser(this).collect { it.role }
	}

	def beforeInsert() {
		encodePassword()
	}

	def beforeUpdate() {
		if (isDirty('password')) {
			encodePassword()
		}
	}

	protected void encodePassword() {
		password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
	}
}

grails-app/domain/docker/registry/web/UserRole.groovy
package docker.registry.web

import org.apache.commons.lang.builder.HashCodeBuilder

class UserRole implements Serializable {

	private static final long serialVersionUID = 1

	User user
	Role role

	boolean equals(other) {
		if (!(other instanceof UserRole)) {
			return false
		}

		other.user?.id == user?.id &&
		other.role?.id == role?.id
	}

	int hashCode() {
		def builder = new HashCodeBuilder()
		if (user) builder.append(user.id)
		if (role) builder.append(role.id)
		builder.toHashCode()
	}

	static UserRole get(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.get()
	}

	static boolean exists(long userId, long roleId) {
		UserRole.where {
			user == User.load(userId) &&
			role == Role.load(roleId)
		}.count() > 0
	}

	static UserRole create(User user, Role role, boolean flush = false) {
		def instance = new UserRole(user: user, role: role)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(User u, Role r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UserRole.where {
			user == User.load(u.id) &&
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(User u, boolean flush = false) {
		if (u == null) return

		UserRole.where {
			user == User.load(u.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static void removeAll(Role r, boolean flush = false) {
		if (r == null) return

		UserRole.where {
			role == Role.load(r.id)
		}.deleteAll()

		if (flush) { UserRole.withSession { it.flush() } }
	}

	static constraints = {
		role validator: { Role r, UserRole ur ->
			if (ur.user == null) return
			boolean existing = false
			UserRole.withNewSession {
				existing = UserRole.exists(ur.user.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['role', 'user']
		version false
	}
}

grails-app/controllers/docker/registry/web/RegistryController.groovy
package docker.registry.web



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RegistryController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Registry.list(params), model:[registryInstanceCount: Registry.count()]
    }

    def show(Registry registryInstance) {
        //FIXME this is really inefficient
        boolean isUp = registryInstance != null && registryInstance.ping()
        respond registryInstance, model: [registryIsUp: isUp]
    }

    def create() {
        respond new Registry(params)
    }

    @Transactional
    def save(Registry registryInstance) {
        if (registryInstance == null) {
            notFound()
            return
        }

        if (registryInstance.hasErrors()) {
            respond registryInstance.errors, view:'create'
            return
        }

        registryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'registry.label', default: 'Registry'), registryInstance.id])
                redirect registryInstance
            }
            '*' { respond registryInstance, [status: CREATED] }
        }
    }

    def edit(Registry registryInstance) {
        respond registryInstance
    }

    @Transactional
    def update(Registry registryInstance) {
        if (registryInstance == null) {
            notFound()
            return
        }

        if (registryInstance.hasErrors()) {
            respond registryInstance.errors, view:'edit'
            return
        }

        registryInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Registry.label', default: 'Registry'), registryInstance.id])
                redirect registryInstance
            }
            '*'{ respond registryInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Registry registryInstance) {

        if (registryInstance == null) {
            notFound()
            return
        }

        registryInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Registry.label', default: 'Registry'), registryInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'registry.label', default: 'Registry'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/docker/registry/web/RepositoryController.groovy
package docker.registry.web

import docker.registry.web.support.Repository
import docker.registry.web.support.RegistryReposView

class RepositoryController {

    def repositoryService
    def registryViewService
    static allowedMethods = [delete: 'DELETE']

    def index() {
        def registries = registryViewService.viewRegistries()
        render view: "index", model: [registryViewSet: registries]
    }

    def show(final int registryId, final String repoName, final String tag, final String imgId) {
        def reg = Registry.get(registryId)
        Repository repository = null

        if (reg) {
            repository = repositoryService.detail(reg, repoName)
        }

        if (!reg || !repository) {
            response.status = 404
        }

        render view: "show", model: [registry: reg, img: repository.images.find { it.id.equals(imgId)}]
    }

    def delete() {
        def repoName = params.repoName
        def registry = params.registry
        def tag = params.tag
        log.info("Deleting image $repoName for registry $registry and tag $tag")
        def reg = Registry.get(registry)
        log.info("Got registry by id $registry ? $reg")
        if (reg) {
            repositoryService.delete(reg, repoName, tag)
        } else {
            response.status = 404
        }
        render view: "delete"
    }
}

grails-app/controllers/docker/registry/web/SearchController.groovy
package docker.registry.web

import docker.registry.web.support.Search

class SearchController {

    def searchService

    def index() { }

    def search(String q) {
        final resultMap = searchService.searchAll(new Search(query: q))
        render view: "results", model: [registryToRepoMap: resultMap]
    }
}

grails-app/views/registry/_form.gsp
<%@ page import="docker.registry.web.Registry" %>

<div class="form-group">
    <label for="apiVersion" class="col-lg-2 control-label"><g:message code="labels.registry.apiVersion"/> *</label>

    <div class="col-lg-2">
        <g:textField name="apiVersion" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.apiVersion}"></g:textField>
    </div>
</div>

<div class="form-group">
    <label for="protocol" class="col-lg-2 control-label"><g:message code="labels.registry.protocol"/> *</label>

    <div class="col-lg-4">
        <g:textField name="protocol" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.protocol}"></g:textField>
    </div>
</div>

<div class="form-group">
    <label for="host" class="col-lg-2 control-label"><g:message code="labels.registry.host"/> *</label>

    <div class="col-lg-4">
        <g:textField name="host" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.host}"></g:textField>
    </div>
</div>

<div class="form-group">
    <label for="port" class="col-lg-2 control-label"><g:message code="labels.registry.port"/> *</label>

    <div class="col-lg-4">
        <g:textField name="port" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.port}"></g:textField>
    </div>
</div>

<div class="form-group">
    <label for="username" class="col-lg-2 control-label"><g:message code="labels.registry.username"/></label>

    <div class="col-lg-4">
        <g:textField name="username" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.username}"></g:textField>
    </div>
</div> 

<div class="form-group">
    <label for="password" class="col-lg-2 control-label"><g:message code="labels.registry.password"/></label>

    <div class="col-lg-4">
        <g:textField name="password" style="cursor: auto;" class="form-control"
                     value="${registryInstance?.password}"></g:textField>
    </div>
</div> 

grails-app/views/registry/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'registry.label', default: 'Registry')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav" role="navigation">
            <g:link class="create" action="create"><button class="btn btn-link" type="button">
                <g:message code="default.new.label" args="[entityName]"/></button></g:link>
            <g:link class="create" action="index"><button class="btn btn-link" type="button">
                <g:message code="default.list.label" args="[entityName]"/></button></g:link>
        </div>



        <div id="create-registry" class="content scaffold-create" role="main">
            <h4><g:message code="default.create.label" args="[entityName]" /></h4>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${registryInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${registryInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>

            <g:form class="form-horizontal" url="[resource:registryInstance, action:'save']" >
                <fieldset>
                    <g:render template="form"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>

        </div>
    </body>
</html>

grails-app/views/registry/edit.gsp
<%@ page import="docker.registry.web.Registry" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'registry.label', default: 'Registry')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>

        <div class="nav" role="navigation">
            <g:link class="create" action="create"><button class="btn btn-link" type="button">
                <g:message code="default.new.label" args="[entityName]"/></button></g:link>
            <g:link class="create" action="index"><button class="btn btn-link" type="button">
                <g:message code="default.list.label" args="[entityName]"/></button></g:link>
        </div>

        <div id="edit-registry" class="content scaffold-edit" role="main">

            <h4><g:message code="default.edit.label" args="[entityName]" /></h4>

            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${registryInstance}">

            <ul class="errors" role="alert">
                <g:eachError bean="${registryInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>

            <g:form class="form-horizontal" url="[resource:registryInstance, action:'update']" method="PUT" >
                <g:hiddenField name="version" value="${registryInstance?.version}" />
                <fieldset class="form">
                    <div class="form-group">
                        <label for="apiVersion" class="col-lg-2 control-label"><g:message code="labels.registry.apiVersion"/> *</label>

                        <div class="col-lg-2">
                            <g:textField name="apiVersion" style="cursor: auto;" class="form-control"
                                         value="${registryInstance?.apiVersion}"></g:textField>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="protocol" class="col-lg-2 control-label"><g:message code="labels.registry.protocol"/> *</label>

                        <div class="col-lg-4">
                            <g:textField name="protocol" style="cursor: auto;" class="form-control"
                                         value="${registryInstance?.protocol}"></g:textField>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="host" class="col-lg-2 control-label"><g:message code="labels.registry.host"/> *</label>

                        <div class="col-lg-4">
                            <g:textField name="host" style="cursor: auto;" class="form-control"
                                         value="${registryInstance?.host}"></g:textField>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="port" class="col-lg-2 control-label"><g:message code="labels.registry.port"/> *</label>

                        <div class="col-lg-4">
                            <g:textField name="port" style="cursor: auto;" class="form-control"
                                         value="${registryInstance?.port}"></g:textField>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="buttons">
                    <g:actionSubmit class="btn btn-primary" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/registry/index.gsp
<%@ page import="docker.registry.web.Registry" %>
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main">
        <g:set var="entityName" value="${message(code: 'registry.label', default: 'Registry')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <div class="nav" role="navigation">
            <g:link class="create" action="create"><button class="btn btn-link" type="button">
                <g:message code="default.new.label" args="[entityName]"/></button></g:link>
            <g:link class="create" action="index"><button class="btn btn-link" type="button">
                <g:message code="default.list.label" args="[entityName]"/></button></g:link>
        </div>
        <div id="list-registry" class="content scaffold-list" role="main">
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <table class="table table-striped table-hover">
			<thead>
					<tr>
						<th>${message(code: 'registry.host.label', default: 'Hostname')}</th>
						<th>${message(code: 'registry.port.label', default: 'Port')}</th>
						<th>${message(code: 'registry.apiVersion.label', default: 'Api Version')}</th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${registryInstanceList}" status="i" var="registryInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${registryInstance.id}">${fieldValue(bean: registryInstance, field: "host")}</g:link></td>
						<td>${fieldValue(bean: registryInstance, field: "port")}</td>
						<td>${fieldValue(bean: registryInstance, field: "apiVersion")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${registryInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/registry/show.gsp
<%@ page import="docker.registry.web.Registry" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'registry.label', default: 'Registry')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>

<div class="nav" role="navigation">
    <g:link class="create" action="create"><button class="btn btn-link" type="button">
        <g:message code="default.new.label" args="[entityName]"/></button></g:link>
    <g:link class="create" action="index"><button class="btn btn-link" type="button">
        <g:message code="default.list.label" args="[entityName]"/></button></g:link>
</div>

<div id="show-registry" class="content scaffold-show" role="main">
    <h4><g:message code="default.show.label" args="[entityName]"/></h4>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>

    <g:form class="form-horizontal" url="[resource:registryInstance, action:'save']" >
        <fieldset>
            <div class="form-group">
                <label for="apiVersion" class="col-lg-2 control-label"><g:message code="labels.registry.apiVersion"/> </label>

                <div class="col-lg-2">
                    <g:textField name="apiVersion" style="cursor: auto;" class="form-control"
                                 value="${registryInstance?.apiVersion}" readonly=""></g:textField>
                </div>
            </div>

            <div class="form-group">
                <label for="protocol" class="col-lg-2 control-label"><g:message code="labels.registry.protocol"/> </label>

                <div class="col-lg-4">
                    <g:textField name="protocol" style="cursor: auto;" class="form-control"
                                 value="${registryInstance?.protocol}" readonly=""></g:textField>
                </div>
            </div>

            <div class="form-group">
                <label for="host" class="col-lg-2 control-label"><g:message code="labels.registry.host"/> </label>

                <div class="col-lg-4">
                    <g:textField name="host" style="cursor: auto;" class="form-control"
                                 value="${registryInstance?.host}" readonly=""></g:textField>
                </div>
            </div>

            <div class="form-group">
                <label for="port" class="col-lg-2 control-label"><g:message code="labels.registry.port"/> </label>

                <div class="col-lg-4">
                    <g:textField name="port" style="cursor: auto;" class="form-control"
                                 value="${registryInstance?.port}" readonly=""></g:textField>
                </div>
            </div>

            <div class="form-group">
                <label class="col-lg-2 control-label"><g:message code="labels.registry.ping"/> </label>

                <div class="col-lg-4">
                     ${registryIsUp ? message(code:"registry.ping.succeeded") : message(code:"registry.ping.failed")}
                </div>
            </div>

        </fieldset>

    </g:form>

    <g:form url="[resource: registryInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="btn btn-primary" action="edit" resource="${registryInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="btn btn-primary" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>